[package]
name = "resize_test"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
iced.workspace = true
iced.features = ["tokio"]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
